bind 0.0.0.0
protected-mode yes
port 6379
appendonly yes
appendfsync everysec
save 900 1
save 300 10
save 60 10000
dir /data
maxmemory-policy noeviction
rename-command FLUSHALL ""
rename-command FLUSHDB ""
